= Output a Transformation to an Attribute or Variable (Design Center)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords:

By default, the Transform component outputs to the payload of a Mule event. You can also output data to a variable or attribute that you create.

== Before you begin
Set up a basic flow that sends the Transform component Input data.

== Procedure
. From the Mapping tab in the Transform component, click the title of the Output column, which should say Output Payload by default.
. Select Add Transformation.
. Select one of these types:
+
* Attributes
* Variable
. Click *Create New Data Type* to create or select a data type for the attribute or variable.
. Map the portion of the Transformer input that you want to output to the attribute or variable.
+
[TIP]
====
You can check your mapping by adding a Logger after the Transformer, for example:
+
* Logger message for an attribute: `message.attributes`
* Logger message for the variable `myVar`: `vars.myVar`
+
When the flow is triggered, the message is posted to the log.
====



== See Also

* xref:mule-message-structure.adoc[Mule Message Structure]: Explains what attributes are.

xref:about-mule-variables.adoc[Variables in Mule Apps]: Explains what flow variables are.
